In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('/content/Bengaluru_House_Data.csv')

In [4]:
data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [5]:
data.shape

(13320, 9)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [7]:
data.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [8]:
data.drop(columns=['area_type','availability','society','balcony'],inplace=True)

In [9]:
data.isna().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [10]:
data[['location', 'size']].isna().all(axis=1)

0        False
1        False
2        False
3        False
4        False
         ...
13315    False
13316    False
13317    False
13318    False
13319    False
Length: 13320, dtype: bool

In [11]:
data.drop(index= data[data['size'].isna()].index,inplace=True)

In [12]:
data['bath'].fillna(data['bath'].mean(), inplace=True)

/tmp/ipykernel_12787/1418771249.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['bath'].fillna(data['bath'].mean(), inplace=True)

In [13]:
data.describe()

               bath         price
count  13304.000000  13304.000000
mean       2.692610    112.582035
std        1.338581    148.988398
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [14]:
data['bhk']= data['size'].str.split().str.get(0).astype(int)

In [15]:
data['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [16]:
def convertRange(x):
  temp = x.split('-')
  if len(temp) == 2:
    return (float(temp[0]) + float(temp[1]))/2
  try:
    return float(x)
  except:
    return None

In [17]:
data['total_sqft']= data['total_sqft'].apply(convertRange)

In [18]:
data['location'].value_counts()

location
Whitefield                         539
Sarjapur  Road                     397
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
KAMAKIYA                             1
Wheelers Road                        1
MM Layout                            1
Devarabeesana Halli                  1
beml layout, basaveshwara nagar      1
Name: count, Length: 1304, dtype: int64

In [19]:
data.describe()

         total_sqft          bath         price           bhk
count  13258.000000  13304.000000  13304.000000  13304.000000
mean    1558.812282      2.692610    112.582035      2.803743
std     1238.432276      1.338581    148.988398      1.294974
min        1.000000      1.000000      8.000000      1.000000
25%     1100.000000      2.000000     50.000000      2.000000
50%     1275.000000      2.000000     72.000000      3.000000
75%     1680.000000      3.000000    120.000000      3.000000
max    52272.000000     40.000000   3600.000000     43.000000

In [20]:
data.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [21]:
data.drop(columns=['size'],inplace=True)

In [22]:
data['price_per_sqft'] = data['price']*100000 / data['total_sqft']

In [23]:
data['location']= data['location'].fillna('').apply(lambda x: x.strip())
location_count = data['location'].value_counts()

In [24]:
location_count_less_10 = location_count[location_count<=10]
location_count_less_10

location
Dairy Circle            10
Nagappa Reddy Layout    10
Nagadevanahalli         10
Ganga Nagar             10
Sector 1 HSR Layout     10
                        ..
Chikkanahalli            1
Halanayakanahalli        1
Park View Layout         1
Xavier Layout            1
Air View Colony          1
Name: count, Length: 1053, dtype: int64

In [25]:
data['location']=data['location'].apply(lambda x: 'other' if x in location_count_less_10 else x)

In [26]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13258.000000  13304.000000  13304.000000  13304.000000    1.325800e+04
mean    1558.812282      2.692610    112.582035      2.803743    7.912634e+03
std     1238.432276      1.338581    148.988398      1.294974    1.064936e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.271229e+03
50%     1275.000000      2.000000     72.000000      3.000000    5.438331e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.313266e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [27]:
data = data[((data['total_sqft'])/data['bhk'])>=300]
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  12514.000000  12514.000000  12514.000000  12514.000000    12514.000000
mean    1593.746383      2.563407    111.398333      2.651670     6307.367132
std     1261.351669      1.077811    152.098807      0.977025     4160.773691
min      300.000000      1.000000      9.000000      1.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.762120
50%     1300.000000      2.000000     70.000000      3.000000     5295.073227
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [28]:
def outlier_remover(df):
  df_output = pd.DataFrame()
  for key, subdf in df.groupby('location'):
    m = np.mean(subdf.price_per_sqft)

    st = np.std(subdf.price_per_sqft)
    gen_df = subdf[(subdf.price_per_sqft > (m-st)) & (subdf.price_per_sqft <= (m+st))]
    df_output = pd.concat([df_output,gen_df],ignore_index=True)
  return df_output
data = outlier_remover(data)
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  10287.000000  10287.000000  10287.000000  10287.000000    10287.000000
mean    1507.548674      2.475097     91.250302      2.574900     5659.971734
std      879.955401      0.979198     86.316523      0.898074     2265.519556
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1109.000000      2.000000     49.000000      2.000000     4250.000000
50%     1285.000000      2.000000     67.000000      2.000000     5176.470588
75%     1650.000000      3.000000    100.000000      3.000000     6428.571429
max    30400.000000     16.000000   2200.000000     16.000000    24509.803922

In [29]:
def bhk_outlier_remover(df):
  exclude_indices = np.array([])
  for location, location_df in df.groupby('location'):
    bhk_stats = {}
    for bhk, bhk_df in location_df.groupby('bhk'):
      bhk_stats[bhk] = {
          'mean': np.mean(bhk_df.price_per_sqft),
          'std': np.std(bhk_df.price_per_sqft),
          'count': bhk_df.shape[0]
      }
      for bhk, bhk_df in location_df.groupby('bhk'):
        stats = bhk_stats.get(bhk-1)
        if stats and stats['count']>5:
          exclude_indices = np.append(exclude_indices, bhk_df[bhk_df.price_per_sqft<=(stats['mean'])].index.values)
  return df.drop(exclude_indices,axis='index')

In [30]:
data = bhk_outlier_remover(data)

In [31]:
data.shape

(7354, 6)

In [32]:
data.drop(columns=['price_per_sqft'],inplace=True)

In [33]:
data.head()

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      2850.0   4.0  428.0    4
1  1st Block Jayanagar      1630.0   3.0  194.0    3
2  1st Block Jayanagar      1875.0   2.0  235.0    3
3  1st Block Jayanagar      1200.0   2.0  130.0    3
4  1st Block Jayanagar      1235.0   2.0  148.0    2

In [34]:
data.to_csv("cleaned_data_house.csv")

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso ,Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [36]:
x = data.drop(columns=['price'])
y = data['price']

In [37]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [38]:
colomn_trans = make_column_transformer((OneHotEncoder(sparse_output=False),['location']),
                                    remainder='passthrough')

In [39]:
scaler = StandardScaler()

In [40]:
lr = LinearRegression()

In [41]:
pipe = make_pipeline(colomn_trans,scaler,lr)

In [42]:
pipe.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [43]:
y_pred_lr = pipe.predict(x_test)

In [44]:
r2_score(y_test,y_pred_lr)

0.8717927187478619

In [45]:
ls = Lasso()

In [46]:
pipel = make_pipeline(colomn_trans,scaler,ls)

In [47]:
pipel.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [48]:
y_pred_ls = pipel.predict(x_test)
r2_score(y_test,y_pred_ls)

0.8675805232902737

In [49]:
rs = Ridge()

In [50]:
piper = make_pipeline(colomn_trans,scaler,rs)

In [51]:
piper.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [52]:
piper.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [53]:
y_pred_rs = piper.predict(x_test)
r2_score(y_test,y_pred_rs)

0.8718748041223432

In [54]:
import pickle

In [55]:
pickle.dump(pipe,open('RidgeModel.pkl','wb'))

In [58]:
f = pickle.load(open('RidgeModel.pkl','rb'))

In [66]:
user_data = pd.DataFrame({
    'location':['1st Phase JP Nagar'],
    'total_sqft':[6000],
    'bath':[6],
    'bhk':[6]})

In [67]:
prediction = f.predict(user_data)

In [68]:
prediction[0]

np.float64(507.78455094513896)